project:
  type: website
  output-dir: docs

website:
  title: "RPAD 702 - Scholarly Foundations of Politics and Administration"
  navbar:
    background: warning
    left:
      - text: "About"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus702.qmd
      - text: "Book List"
        file: booklist.qmd
      - text: "Assignment"
        file: assignments.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

