---
title: "Assignment"
---

Choose one question from each section. Use answering the question to guide your literature review. A thorough answer will draw on related readings from the class reading list and literature in academic journals and government and think tank reports related to the topic over time. Your final paper should be between 20 and 30 pages double-spaced (excluding figures and references).

::: calout-important
The 30 page top limit is a maximimum. Do not exceed it.
:::

### Section I. Grand theories.
A long-standing effort has been made in the social sciences to construct grand theories of human and societal behaviors, philosophies, and activities.

1.	Choose two major theories about how administrators of government organize and act. Describe, in detail, the arguments of the theories and the value they have in application when considering how to analyze government or operate its functions. Describe the empirical evidence base for each theory and how the theories have changed over time in response to evidence or updated work.

2.	Choose two major theories about democracy and how public actors share preferences for government action and corresponding government action. Provide a detailed description of the two theories and the major works that have shaped those theories over time. Summarize the empirical evidence base for each theory up to now and consider how the theories might differ in their recommendations for ensuring authoritarianism does not supplant democratic governance.

### Section II. Application (only one option and required)
1.	Consider an area of government of interest to you (a policy area, an agency of particular interest, a government function of interest, etc.) through the lens of the theories identified in Section I. What are the major issues suggested by the theory that would be of concern in administratively or democratically in that area of government? What research has been done in those areas of concern? What have been the approaches used in that research and what have the researchers generally found? How do those results reflect on the bounds of the theory?

### Section III. Alignment of research design and theory (only one option and required)
1.	Consider both the theories you have examined from section I and the applications in Section II. First, describe the methodological approach you think would best be used to address gaps in the knowledge base you have summarized. Second, describe the data you would collect (qualitative or quantitative), the process you would use for collecting the data, and design you would use for analyzing that data to fill the gaps you identify in the knowledge base. Defend your approach with citations to extant methodological literature.
