---
title: "Book List"
---

## Required Books

- Michael J. Sandel. 2009. *Justice: What’s the Right Thing to Do?* New York, NY: Farrar, Straus, and Giroux.
- John Dewey. 1954. *The Public and Its Problems.* Athens, OH: Swallow Press Books.
- Robert F. Durant. 2014. *Why Public Service Matters: Public Managers, Public Policy, and Democracy.* New York, NY: Palgrave Macmillan.
- Frank J. Goodnow. 1900. *Politics and Administration.* New York, NY: Macmillan.
- James G. March and Johan P. Olsen. 1989. *Rediscovering Institutions: The Organizational Basis of Politics.* New York, NY: The Free Press.
- Alexander Hamilton, James Madison, and John Jay. 2003. *The Federalist Papers.* New York, NY: Signet Classic.
- Ralph Ketcham. 2003.*The Anti-Federalist Papers and the Constitutional Convention Debates.* New York, NY: Signet Classic.
- John Rawls. 1971. *A Theory of Justice.* Cambridge, MA: Belknap Press.
- Charles W. Anderson. 1990. *Pragmatic Liberalism.* Chicago, IL: The University of Chicago Press.
- Stephen Skowronek. 1982. *Building a New American State: The Expansion of National Administrative Capacities, 1877-1920.* New York, NY: Cambridge University Press.
- John A. Rohr. 1986. *To Run a Constitution: The Legitimacy of the Administrative State.* Lawrence, KS: University of Kansas Press.
- Anthony M. Bertelli and Laurence E. Lynn, Jr. 2006. *Madison’s Managers: Public Administration and the Constitution.* Baltimore, MD: Johns Hopkins University Press.
- Paul E. Peterson. 1995. “Functional and Legislative Theories of Federalism,” in *The Price of Federalism.* Washington, DC: The Brookings Institution.
- William G. Resh. 2015. *Rethinking the Administrative Presidency: Trust, Intellectual Capital, and Appointee-Careerist Relations in the George W. Bush Administration.* Baltimore, MD: Johns Hopkins University Press.
- Malcom M. Feeley and Edward L. Rubin. 2000. *Judicial Policy Making and the Modern State: How the Courts Reformed America’s Prisons.* Cambridge, UK: Cambridge University Press.
- Emmette S. Redford. 1969. *Democracy in the Administrative State.* New York, NY: Oxford University Press.
- Douglas Yates. 1987. *Bureaucratic Democracy: The Search for Democracy and Efficiency in American Government.* Cambridge, MA: Harvard University Press.
- Robert D. Putnam. 2000. *Bowling Alone: The Collapse and Revival of American Community.* New York, NY: Simon & Schuster Paperbacks.
- Sandford Borins. 2011. *Governing fables: Learning from public sector narratives*. IAP.
- Anthony Downs. 1957. *An Economic Theory of Democracy.* New York, NY: Harper & Row.
- Mancur Olson. 1965. *The Logic of Collective Action: Public Goods and the Theory of Groups.* Cambridge, MA: Harvard University Press.
- William A. Niskanen, Jr. 1971. *Bureaucracy and Representative Government.* Chicago, IL: Aldine.
- Theodore J. Lowi. 1979. *The End of Liberalism: The Second Republic of the United States.* New York, NY: W. W. Norton & Company.
- Terry M. Moe. 1980. *The Organization of Interests: Incentives and the Internal Dynamics of Political Interest Groups.* Chicago, IL: University of Chicago Press.
- Francis E. Rourke. 1984. *Bureaucracy, Politics, and Public Policy.* Boston, MA: Little, Brown and Company.
- Katherine Levine Einstein, David M. Glick, and Maxwell Palmer. 2019. *Neighborhood Defenders: Participatory Politics and America's Housing Crisis*. Cambridge University Press.
- William F. West. 1985. *Administrative Rulemaking: Politics and Processes.* Westport, CT: Greenwood Press.
- Elinor Ostrom. 1990. *Governing the Commons: The Evolution of Institutions for Collective Action.* New York, NY: Cambridge University Press.
- Charles T. Goodsell. 1983. *The Case for Bureaucracy: A Public Administration Polemic.* Chatham, NJ: Chatham House Publishers.
- Joel D. Aberbach and Bert A. Rockman. 2000. *In the Web of Politics: Three Decades of the U.S. Federal Executive.* Washington, DC: Brookings Institution Press.
- John Brehm and Scott Gates. 2002. *Working, Shirking, and Sabotage: Bureaucratic Response to a Democratic Public.* Ann Arbor, MI: University of Michigan Press.
- Daniel P. Carpenter. 2001. *The Forging of Bureaucratic Autonomy: Reputations, Networks, and Policy Innovation in Executive Agencies, 1862-1928.* Princeton, NJ: Princeton University Press.
- Guy Peters. 2010. *The Politics of Bureaucracy: An Introduction to Comparative Public Administration.* New York, NY: Routledge.
- Herd, P. and Moynihan, D.P., 2019. *Administrative Burden: Policymaking by Other Means.* Russell Sage Foundation.
- Donald F. Kettl. 2015. *The Transformation of Governance: Public Administration for the Twenty-First Century.* Baltimore, MD: Johns Hopkins University Press.
- Kenneth J. Meier and Laurence O’Toole, Jr. 2006. *Bureaucracy in a Democratic State: A Governance Perspective.* Baltimore, MD: Johns Hopkins University Press.
- Harold Seidman. 1998. *Politics, Position, and Power: The Dynamics of Federal Organization.* New York, NY: Oxford University Press.
- Mark H. Moore. 1995. *Creating Public Value: Strategic Management in Government.* Cambridge, MA: Harvard University Press.
- Barry Bozeman. 2007. *Public Values and Public Interest: Counterbalancing Economic Individualism.* Washington, DC: Georgetown University Press.
- George Frederickson. 2010. *Social Equity and Public Administration: Origins, Developments, and Applications.* Armonk, NY: M.E. Sharpe.
- H. George Frederickson. 1997. *The Spirit of Public Administration.* San Francisco, CA: Jossey-Bass.
- John A. Rohr. 2002. *Civil Servants and Their Constitutions.* Lawrence, KS: University of Kansas Press.
- Paul Light. 1999. *The New Public Service.* Washington, DC: Brookings Institution Press.

## Recommended Books

- David R. Morgan, Robert E. England, and John P. Pelissero. 2007. “Cities and the System of Intergovernmental Relations,” in *Managing Urban America* (6th ed.). Washington, DC: CQ Press.
- Graham T. Allison. 1980. *Public and Private Management: Are They Fundamentally Alike in All Unimportant Respects?*. Cambridge, MA: Harvard University Press.
- Irene S. Rubin. 1990. *The Politics of Public Budgeting.* Chatham, NJ: Chatham House Publishers.
- Donald P. Moynihan. 2008. *The Dynamics of Performance Management: Constructing Information and Reform.* Washington, DC: Georgetown University Press.